### PR TITLE
Dotnetcore support

### PR DESCRIPTION
**Pull request by naile**
Migrated .sln to VS 2017 and new csproj format
Multitargeting for net46, netstandard1.3 and netstandard2.0

### CODE REVIEW

**Comment by karl-sjogren** [comment]
This looks great, I'll merge it and fix up some other things to get it inline with my other libraries and then publish a new nuget package.

**Comment by karl-sjogren** [comment]
Do we really need the net461 target? The project can be built against netstandard1.0 which means it should work with net45 and up.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by naile** [comment]
In my experience it's usually a lot less error-prone to target the full framework, if you want to support it. Not all full framework projects can reference packages targeting netstandard without taking a dependency on the NETStandard.Library, https://www.nuget.org/packages/NETStandard.Library/

**Comment by karl-sjogren** [comment]
Ok, fair enough. I've changed the project to multitarget with net46 if built on Windows so I can keep my existing Travis setup and still develop on OSX. I just have to remember to publish any future updates from Windows.

The package has been submitted and should be available at https://www.nuget.org/packages/Shorthand.Geodesy/1.2.0 within the hour.

**Pull request merged**
